
package cliente.prestamo;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.2
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "PrestamoYaExisteExcepcion", targetNamespace = "http://publicadores/")
public class PrestamoYaExisteExcepcion_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PrestamoYaExisteExcepcion faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PrestamoYaExisteExcepcion_Exception(String message, PrestamoYaExisteExcepcion faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PrestamoYaExisteExcepcion_Exception(String message, PrestamoYaExisteExcepcion faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: cliente.prestamo.PrestamoYaExisteExcepcion
     */
    public PrestamoYaExisteExcepcion getFaultInfo() {
        return faultInfo;
    }

}
